use_frameworks!

platform :ios, '10.0'

target 'MKLoRaWAN-AD_Example' do
  pod 'MKLoRaWAN-AD', :path => '../'

  target 'MKLoRaWAN-AD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
